ROBOCOPY .\upload_v2.3.x-3.x\system\library\processingkz .\upload_v2.0.x-2.2\system\library\processingkz\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\view\javascript .\upload_v2.0.x-2.2\admin\view\javascript\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\view\stylesheet .\upload_v2.0.x-2.2\admin\view\stylesheet\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\view\template\extension\payment .\upload_v2.0.x-2.2\admin\view\template\payment\ processingkz.tpl /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\view\template\sale .\upload_v2.0.x-2.2\admin\view\template\sale\ visa*.tpl /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\model .\upload_v2.0.x-2.2\admin\model\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\language .\upload_v2.0.x-2.2\admin\language\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\language\en-gb\extension .\upload_v2.0.x-2.2\admin\language\english\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\language\ru-ru\extension .\upload_v2.0.x-2.2\admin\language\russian\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\controller\extension .\upload_v2.0.x-2.2\admin\controller\ * /S
ROBOCOPY .\upload_v2.3.x-3.x\admin\controller\sale .\upload_v2.0.x-2.2\admin\controller\sale\ * /S
