//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace TestMerchantWebsite.CNPMerchantWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CNPMerchantWebServiceSoap11Binding", Namespace="http://kz.processing.cnp.merchant_ws/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalTransactionStatus))]
    public partial class CNPMerchantWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback completeRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback startTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback refundTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRegistrationStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback completeTransactionExOperationCompleted;
        
        private System.Threading.SendOrPostCallback startRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getExtendedTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransactionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback completeTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CNPMerchantWebService() {
            this.Url = "https://test.processing.kz/CNPMerchantWebServices/services/CNPMerchantWebService." +
                "CNPMerchantWebServiceHttpsSoap11Endpoint/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event completeRegistrationCompletedEventHandler completeRegistrationCompleted;
        
        /// <remarks/>
        public event startTransactionCompletedEventHandler startTransactionCompleted;
        
        /// <remarks/>
        public event refundTransactionCompletedEventHandler refundTransactionCompleted;
        
        /// <remarks/>
        public event getRegistrationStatusCompletedEventHandler getRegistrationStatusCompleted;
        
        /// <remarks/>
        public event completeTransactionExCompletedEventHandler completeTransactionExCompleted;
        
        /// <remarks/>
        public event startRegistrationCompletedEventHandler startRegistrationCompleted;
        
        /// <remarks/>
        public event getVersionCompletedEventHandler getVersionCompleted;
        
        /// <remarks/>
        public event getExtendedTransactionStatusCompletedEventHandler getExtendedTransactionStatusCompleted;
        
        /// <remarks/>
        public event getTransactionStatusCompletedEventHandler getTransactionStatusCompleted;
        
        /// <remarks/>
        public event completeTransactionCompletedEventHandler completeTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:completeRegistration", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void completeRegistration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr, bool registrationSuccess, [System.Xml.Serialization.XmlIgnoreAttribute()] bool registrationSuccessSpecified, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("completeRegistration", new object[] {
                        merchantId,
                        referenceNr,
                        registrationSuccess,
                        registrationSuccessSpecified});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void completeRegistrationAsync(string merchantId, string referenceNr, bool registrationSuccess, bool registrationSuccessSpecified) {
            this.completeRegistrationAsync(merchantId, referenceNr, registrationSuccess, registrationSuccessSpecified, null);
        }
        
        /// <remarks/>
        public void completeRegistrationAsync(string merchantId, string referenceNr, bool registrationSuccess, bool registrationSuccessSpecified, object userState) {
            if ((this.completeRegistrationOperationCompleted == null)) {
                this.completeRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompleteRegistrationOperationCompleted);
            }
            this.InvokeAsync("completeRegistration", new object[] {
                        merchantId,
                        referenceNr,
                        registrationSuccess,
                        registrationSuccessSpecified}, this.completeRegistrationOperationCompleted, userState);
        }
        
        private void OncompleteRegistrationOperationCompleted(object arg) {
            if ((this.completeRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.completeRegistrationCompleted(this, new completeRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:startTransaction", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StartTransactionResult startTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TransactionDetails transaction) {
            object[] results = this.Invoke("startTransaction", new object[] {
                        transaction});
            return ((StartTransactionResult)(results[0]));
        }
        
        /// <remarks/>
        public void startTransactionAsync(TransactionDetails transaction) {
            this.startTransactionAsync(transaction, null);
        }
        
        /// <remarks/>
        public void startTransactionAsync(TransactionDetails transaction, object userState) {
            if ((this.startTransactionOperationCompleted == null)) {
                this.startTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstartTransactionOperationCompleted);
            }
            this.InvokeAsync("startTransaction", new object[] {
                        transaction}, this.startTransactionOperationCompleted, userState);
        }
        
        private void OnstartTransactionOperationCompleted(object arg) {
            if ((this.startTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.startTransactionCompleted(this, new startTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:refundTransaction", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void refundTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string refundAmount, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string description, [System.Xml.Serialization.XmlElementAttribute("goodsToRefund", IsNullable=true)] GoodsItem[] goodsToRefund, [System.Xml.Serialization.XmlElementAttribute("additionalInformation", IsNullable=true)] AdditionalInformation[] additionalInformation, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("refundTransaction", new object[] {
                        merchantId,
                        password,
                        referenceNr,
                        refundAmount,
                        description,
                        goodsToRefund,
                        additionalInformation});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void refundTransactionAsync(string merchantId, string password, string referenceNr, string refundAmount, string description, GoodsItem[] goodsToRefund, AdditionalInformation[] additionalInformation) {
            this.refundTransactionAsync(merchantId, password, referenceNr, refundAmount, description, goodsToRefund, additionalInformation, null);
        }
        
        /// <remarks/>
        public void refundTransactionAsync(string merchantId, string password, string referenceNr, string refundAmount, string description, GoodsItem[] goodsToRefund, AdditionalInformation[] additionalInformation, object userState) {
            if ((this.refundTransactionOperationCompleted == null)) {
                this.refundTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrefundTransactionOperationCompleted);
            }
            this.InvokeAsync("refundTransaction", new object[] {
                        merchantId,
                        password,
                        referenceNr,
                        refundAmount,
                        description,
                        goodsToRefund,
                        additionalInformation}, this.refundTransactionOperationCompleted, userState);
        }
        
        private void OnrefundTransactionOperationCompleted(object arg) {
            if ((this.refundTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.refundTransactionCompleted(this, new refundTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getRegistrationStatus", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StoredRegistrationStatus getRegistrationStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr) {
            object[] results = this.Invoke("getRegistrationStatus", new object[] {
                        merchantId,
                        referenceNr});
            return ((StoredRegistrationStatus)(results[0]));
        }
        
        /// <remarks/>
        public void getRegistrationStatusAsync(string merchantId, string referenceNr) {
            this.getRegistrationStatusAsync(merchantId, referenceNr, null);
        }
        
        /// <remarks/>
        public void getRegistrationStatusAsync(string merchantId, string referenceNr, object userState) {
            if ((this.getRegistrationStatusOperationCompleted == null)) {
                this.getRegistrationStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRegistrationStatusOperationCompleted);
            }
            this.InvokeAsync("getRegistrationStatus", new object[] {
                        merchantId,
                        referenceNr}, this.getRegistrationStatusOperationCompleted, userState);
        }
        
        private void OngetRegistrationStatusOperationCompleted(object arg) {
            if ((this.getRegistrationStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRegistrationStatusCompleted(this, new getRegistrationStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:completeTransactionEx", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void completeTransactionEx([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr, bool transactionSuccess, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transactionSuccessSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string overrideAmount, [System.Xml.Serialization.XmlElementAttribute("goods", IsNullable=true)] GoodsItem[] goods, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("completeTransactionEx", new object[] {
                        merchantId,
                        referenceNr,
                        transactionSuccess,
                        transactionSuccessSpecified,
                        overrideAmount,
                        goods});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void completeTransactionExAsync(string merchantId, string referenceNr, bool transactionSuccess, bool transactionSuccessSpecified, string overrideAmount, GoodsItem[] goods) {
            this.completeTransactionExAsync(merchantId, referenceNr, transactionSuccess, transactionSuccessSpecified, overrideAmount, goods, null);
        }
        
        /// <remarks/>
        public void completeTransactionExAsync(string merchantId, string referenceNr, bool transactionSuccess, bool transactionSuccessSpecified, string overrideAmount, GoodsItem[] goods, object userState) {
            if ((this.completeTransactionExOperationCompleted == null)) {
                this.completeTransactionExOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompleteTransactionExOperationCompleted);
            }
            this.InvokeAsync("completeTransactionEx", new object[] {
                        merchantId,
                        referenceNr,
                        transactionSuccess,
                        transactionSuccessSpecified,
                        overrideAmount,
                        goods}, this.completeTransactionExOperationCompleted, userState);
        }
        
        private void OncompleteTransactionExOperationCompleted(object arg) {
            if ((this.completeTransactionExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.completeTransactionExCompleted(this, new completeTransactionExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:startRegistration", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StartRegistrationResult startRegistration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RegistrationDetails registration) {
            object[] results = this.Invoke("startRegistration", new object[] {
                        registration});
            return ((StartRegistrationResult)(results[0]));
        }
        
        /// <remarks/>
        public void startRegistrationAsync(RegistrationDetails registration) {
            this.startRegistrationAsync(registration, null);
        }
        
        /// <remarks/>
        public void startRegistrationAsync(RegistrationDetails registration, object userState) {
            if ((this.startRegistrationOperationCompleted == null)) {
                this.startRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstartRegistrationOperationCompleted);
            }
            this.InvokeAsync("startRegistration", new object[] {
                        registration}, this.startRegistrationOperationCompleted, userState);
        }
        
        private void OnstartRegistrationOperationCompleted(object arg) {
            if ((this.startRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.startRegistrationCompleted(this, new startRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getVersion", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getVersionResponse", Namespace="http://kz.processing.cnp.merchant_ws/xsd")]
        public getVersionResponse getVersion() {
            object[] results = this.Invoke("getVersion", new object[0]);
            return ((getVersionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getVersionAsync() {
            this.getVersionAsync(null);
        }
        
        /// <remarks/>
        public void getVersionAsync(object userState) {
            if ((this.getVersionOperationCompleted == null)) {
                this.getVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersionOperationCompleted);
            }
            this.InvokeAsync("getVersion", new object[0], this.getVersionOperationCompleted, userState);
        }
        
        private void OngetVersionOperationCompleted(object arg) {
            if ((this.getVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersionCompleted(this, new getVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getExtendedTransactionStatus", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StoredTransactionStatusExtended getExtendedTransactionStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr) {
            object[] results = this.Invoke("getExtendedTransactionStatus", new object[] {
                        merchantId,
                        referenceNr});
            return ((StoredTransactionStatusExtended)(results[0]));
        }
        
        /// <remarks/>
        public void getExtendedTransactionStatusAsync(string merchantId, string referenceNr) {
            this.getExtendedTransactionStatusAsync(merchantId, referenceNr, null);
        }
        
        /// <remarks/>
        public void getExtendedTransactionStatusAsync(string merchantId, string referenceNr, object userState) {
            if ((this.getExtendedTransactionStatusOperationCompleted == null)) {
                this.getExtendedTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExtendedTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("getExtendedTransactionStatus", new object[] {
                        merchantId,
                        referenceNr}, this.getExtendedTransactionStatusOperationCompleted, userState);
        }
        
        private void OngetExtendedTransactionStatusOperationCompleted(object arg) {
            if ((this.getExtendedTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExtendedTransactionStatusCompleted(this, new getExtendedTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getTransactionStatus", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public StoredTransactionStatus getTransactionStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr) {
            object[] results = this.Invoke("getTransactionStatus", new object[] {
                        merchantId,
                        referenceNr});
            return ((StoredTransactionStatus)(results[0]));
        }
        
        /// <remarks/>
        public void getTransactionStatusAsync(string merchantId, string referenceNr) {
            this.getTransactionStatusAsync(merchantId, referenceNr, null);
        }
        
        /// <remarks/>
        public void getTransactionStatusAsync(string merchantId, string referenceNr, object userState) {
            if ((this.getTransactionStatusOperationCompleted == null)) {
                this.getTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("getTransactionStatus", new object[] {
                        merchantId,
                        referenceNr}, this.getTransactionStatusOperationCompleted, userState);
        }
        
        private void OngetTransactionStatusOperationCompleted(object arg) {
            if ((this.getTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransactionStatusCompleted(this, new getTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:completeTransaction", RequestNamespace="http://kz.processing.cnp.merchant_ws/xsd", ResponseNamespace="http://kz.processing.cnp.merchant_ws/xsd", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void completeTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string merchantId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string referenceNr, bool transactionSuccess, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transactionSuccessSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string overrideAmount, out bool @return, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool returnSpecified) {
            object[] results = this.Invoke("completeTransaction", new object[] {
                        merchantId,
                        referenceNr,
                        transactionSuccess,
                        transactionSuccessSpecified,
                        overrideAmount});
            @return = ((bool)(results[0]));
            returnSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void completeTransactionAsync(string merchantId, string referenceNr, bool transactionSuccess, bool transactionSuccessSpecified, string overrideAmount) {
            this.completeTransactionAsync(merchantId, referenceNr, transactionSuccess, transactionSuccessSpecified, overrideAmount, null);
        }
        
        /// <remarks/>
        public void completeTransactionAsync(string merchantId, string referenceNr, bool transactionSuccess, bool transactionSuccessSpecified, string overrideAmount, object userState) {
            if ((this.completeTransactionOperationCompleted == null)) {
                this.completeTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncompleteTransactionOperationCompleted);
            }
            this.InvokeAsync("completeTransaction", new object[] {
                        merchantId,
                        referenceNr,
                        transactionSuccess,
                        transactionSuccessSpecified,
                        overrideAmount}, this.completeTransactionOperationCompleted, userState);
        }
        
        private void OncompleteTransactionOperationCompleted(object arg) {
            if ((this.completeTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.completeTransactionCompleted(this, new completeTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class TransactionDetails {
        
        private Address billingAddressField;
        
        private string cardIdField;
        
        private int currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private string customerReferenceField;
        
        private string descriptionField;
        
        private GoodsItem[] goodsListField;
        
        private string languageCodeField;
        
        private AdditionalInformation[] merchantAdditionalInformationListField;
        
        private string merchantIdField;
        
        private string merchantLocalDateTimeField;
        
        private string orderIdField;
        
        private int paymentTypeField;
        
        private bool paymentTypeFieldSpecified;
        
        private string purchaserEmailField;
        
        private string purchaserNameField;
        
        private string purchaserPhoneField;
        
        private string returnURLField;
        
        private string terminalIDField;
        
        private string totalAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address billingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
            }
        }
        
        /// <remarks/>
        public int currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyCodeSpecified {
            get {
                return this.currencyCodeFieldSpecified;
            }
            set {
                this.currencyCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("goodsList", IsNullable=true)]
        public GoodsItem[] goodsList {
            get {
                return this.goodsListField;
            }
            set {
                this.goodsListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("merchantAdditionalInformationList", IsNullable=true)]
        public AdditionalInformation[] merchantAdditionalInformationList {
            get {
                return this.merchantAdditionalInformationListField;
            }
            set {
                this.merchantAdditionalInformationListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantLocalDateTime {
            get {
                return this.merchantLocalDateTimeField;
            }
            set {
                this.merchantLocalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public int paymentType {
            get {
                return this.paymentTypeField;
            }
            set {
                this.paymentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentTypeSpecified {
            get {
                return this.paymentTypeFieldSpecified;
            }
            set {
                this.paymentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserEmail {
            get {
                return this.purchaserEmailField;
            }
            set {
                this.purchaserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserName {
            get {
                return this.purchaserNameField;
            }
            set {
                this.purchaserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserPhone {
            get {
                return this.purchaserPhoneField;
            }
            set {
                this.purchaserPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnURL {
            get {
                return this.returnURLField;
            }
            set {
                this.returnURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string terminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class Address {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string countryField;
        
        private string countyField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string county {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class StoredTransactionStatus {
        
        private AdditionalInformation[] additionalInformationField;
        
        private string amountAuthorisedField;
        
        private string amountRefundedField;
        
        private string amountRequestedField;
        
        private string amountSettledField;
        
        private string authCodeField;
        
        private GoodsItem[] goodsField;
        
        private string merchantLocalDateTimeField;
        
        private string merchantOnlineAddressField;
        
        private string orderIdField;
        
        private string purchaserEmailField;
        
        private string purchaserNameField;
        
        private string purchaserPhoneField;
        
        private string transactionCurrencyCodeField;
        
        private string transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalInformation", IsNullable=true)]
        public AdditionalInformation[] additionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountAuthorised {
            get {
                return this.amountAuthorisedField;
            }
            set {
                this.amountAuthorisedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountRefunded {
            get {
                return this.amountRefundedField;
            }
            set {
                this.amountRefundedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountRequested {
            get {
                return this.amountRequestedField;
            }
            set {
                this.amountRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountSettled {
            get {
                return this.amountSettledField;
            }
            set {
                this.amountSettledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("goods", IsNullable=true)]
        public GoodsItem[] goods {
            get {
                return this.goodsField;
            }
            set {
                this.goodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantLocalDateTime {
            get {
                return this.merchantLocalDateTimeField;
            }
            set {
                this.merchantLocalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantOnlineAddress {
            get {
                return this.merchantOnlineAddressField;
            }
            set {
                this.merchantOnlineAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserEmail {
            get {
                return this.purchaserEmailField;
            }
            set {
                this.purchaserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserName {
            get {
                return this.purchaserNameField;
            }
            set {
                this.purchaserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserPhone {
            get {
                return this.purchaserPhoneField;
            }
            set {
                this.purchaserPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionCurrencyCode {
            get {
                return this.transactionCurrencyCodeField;
            }
            set {
                this.transactionCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class AdditionalInformation {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class GoodsItem {
        
        private string amountField;
        
        private int currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private string merchantsGoodsIDField;
        
        private string nameOfGoodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public int currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyCodeSpecified {
            get {
                return this.currencyCodeFieldSpecified;
            }
            set {
                this.currencyCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantsGoodsID {
            get {
                return this.merchantsGoodsIDField;
            }
            set {
                this.merchantsGoodsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nameOfGoods {
            get {
                return this.nameOfGoodsField;
            }
            set {
                this.nameOfGoodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class StoredTransactionStatusExtended {
        
        private string cardIssuerCountryField;
        
        private string maskedCardNumberField;
        
        private string purchaserIpAddressField;
        
        private string verified3DField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardIssuerCountry {
            get {
                return this.cardIssuerCountryField;
            }
            set {
                this.cardIssuerCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maskedCardNumber {
            get {
                return this.maskedCardNumberField;
            }
            set {
                this.maskedCardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserIpAddress {
            get {
                return this.purchaserIpAddressField;
            }
            set {
                this.purchaserIpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string verified3D {
            get {
                return this.verified3DField;
            }
            set {
                this.verified3DField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class RegistrationDetails {
        
        private int currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private string customerReferenceField;
        
        private string languageCodeField;
        
        private string merchantIdField;
        
        private string merchantLocalDateTimeField;
        
        private string purchaserEmailField;
        
        private string purchaserNameField;
        
        private string purchaserPhoneField;
        
        private string returnURLField;
        
        private string terminalIDField;
        
        private string totalAmountField;
        
        /// <remarks/>
        public int currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyCodeSpecified {
            get {
                return this.currencyCodeFieldSpecified;
            }
            set {
                this.currencyCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantLocalDateTime {
            get {
                return this.merchantLocalDateTimeField;
            }
            set {
                this.merchantLocalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserEmail {
            get {
                return this.purchaserEmailField;
            }
            set {
                this.purchaserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserName {
            get {
                return this.purchaserNameField;
            }
            set {
                this.purchaserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserPhone {
            get {
                return this.purchaserPhoneField;
            }
            set {
                this.purchaserPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string returnURL {
            get {
                return this.returnURLField;
            }
            set {
                this.returnURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string terminalID {
            get {
                return this.terminalIDField;
            }
            set {
                this.terminalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoredRegistrationStatus))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class InternalTransactionStatus {
        
        private AdditionalInformation[] additionalInformationField;
        
        private string amountAuthorisedField;
        
        private string amountRefundedField;
        
        private string amountRequestedField;
        
        private string amountSettledField;
        
        private string authCodeField;
        
        private string binField;
        
        private string eciField;
        
        private GoodsItem[] goodsField;
        
        private string lastDigitsPanField;
        
        private string merchantLocalDateTimeField;
        
        private string merchantOnlineAddressField;
        
        private string orderIdField;
        
        private string purchaserEmailField;
        
        private string purchaserIdAddressField;
        
        private string purchaserNameField;
        
        private string purchaserPhoneField;
        
        private string transactionCurrencyCodeField;
        
        private string transactionStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalInformation", IsNullable=true)]
        public AdditionalInformation[] additionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountAuthorised {
            get {
                return this.amountAuthorisedField;
            }
            set {
                this.amountAuthorisedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountRefunded {
            get {
                return this.amountRefundedField;
            }
            set {
                this.amountRefundedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountRequested {
            get {
                return this.amountRequestedField;
            }
            set {
                this.amountRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amountSettled {
            get {
                return this.amountSettledField;
            }
            set {
                this.amountSettledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bin {
            get {
                return this.binField;
            }
            set {
                this.binField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string eci {
            get {
                return this.eciField;
            }
            set {
                this.eciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("goods", IsNullable=true)]
        public GoodsItem[] goods {
            get {
                return this.goodsField;
            }
            set {
                this.goodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lastDigitsPan {
            get {
                return this.lastDigitsPanField;
            }
            set {
                this.lastDigitsPanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantLocalDateTime {
            get {
                return this.merchantLocalDateTimeField;
            }
            set {
                this.merchantLocalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string merchantOnlineAddress {
            get {
                return this.merchantOnlineAddressField;
            }
            set {
                this.merchantOnlineAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserEmail {
            get {
                return this.purchaserEmailField;
            }
            set {
                this.purchaserEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserIdAddress {
            get {
                return this.purchaserIdAddressField;
            }
            set {
                this.purchaserIdAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserName {
            get {
                return this.purchaserNameField;
            }
            set {
                this.purchaserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string purchaserPhone {
            get {
                return this.purchaserPhoneField;
            }
            set {
                this.purchaserPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionCurrencyCode {
            get {
                return this.transactionCurrencyCodeField;
            }
            set {
                this.transactionCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.common.cnp.processing.kz/xsd")]
    public partial class StoredRegistrationStatus : InternalTransactionStatus {
        
        private string cardIdField;
        
        private string maskedPanField;
        
        private string registrationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maskedPan {
            get {
                return this.maskedPanField;
            }
            set {
                this.maskedPanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string registrationStatus {
            get {
                return this.registrationStatusField;
            }
            set {
                this.registrationStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StartRegistrationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.merchant_web_services.cnp.processing.kz/xsd")]
    public partial class StartTransactionResult {
        
        private string customerReferenceField;
        
        private string errorDescriptionField;
        
        private string redirectURLField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerReference {
            get {
                return this.customerReferenceField;
            }
            set {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string redirectURL {
            get {
                return this.redirectURLField;
            }
            set {
                this.redirectURLField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans.merchant_web_services.cnp.processing.kz/xsd")]
    public partial class StartRegistrationResult : StartTransactionResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kz.processing.cnp.merchant_ws/xsd")]
    public partial class getVersionResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void completeRegistrationCompletedEventHandler(object sender, completeRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class completeRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal completeRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void startTransactionCompletedEventHandler(object sender, startTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class startTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal startTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StartTransactionResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StartTransactionResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void refundTransactionCompletedEventHandler(object sender, refundTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class refundTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal refundTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getRegistrationStatusCompletedEventHandler(object sender, getRegistrationStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRegistrationStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRegistrationStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoredRegistrationStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoredRegistrationStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void completeTransactionExCompletedEventHandler(object sender, completeTransactionExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class completeTransactionExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal completeTransactionExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void startRegistrationCompletedEventHandler(object sender, startRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class startRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal startRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StartRegistrationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StartRegistrationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVersionCompletedEventHandler(object sender, getVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getVersionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getVersionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getExtendedTransactionStatusCompletedEventHandler(object sender, getExtendedTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExtendedTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExtendedTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoredTransactionStatusExtended Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoredTransactionStatusExtended)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTransactionStatusCompletedEventHandler(object sender, getTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoredTransactionStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoredTransactionStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void completeTransactionCompletedEventHandler(object sender, completeTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class completeTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal completeTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool @return {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool returnSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591